### ISSUE TITLE
Internal error: ArgumentError: comparison of Integer with nil failed

### ISSUE THREAD

**Issue by mtahiue** [atech/postal#128]
Hi

I have this message on my postal instance

An internal error occurred while sending this message. This message will be retried automatically. This this persists, contact support for assistance.

All messages are in ERROR state
This is  a worker.1 log extract

```
[APSRJTW8ZX] Lock acquired for queued message 87
[APSRJTW8ZX] Found 0 associated messages to process at the same time (batch key: outgoing-mywebsite.com)
[APSRJTW8ZX] [5::11 87] Got queued message with exclusive lock
[APSRJTW8ZX] [5::11 87] Internal error: ArgumentError: comparison of Integer with nil failed
[APSRJTW8ZX] [5::11 87] /opt/postal/app/jobs/unqueue_message_job.rb:54:in `>='
[APSRJTW8ZX] [5::11 87] /opt/postal/app/jobs/unqueue_message_job.rb:54:in `block in perform'
[APSRJTW8ZX] [5::11 87] /opt/postal/app/jobs/unqueue_message_job.rb:30:in `each'
[APSRJTW8ZX] [5::11 87] /opt/postal/app/jobs/unqueue_message_job.rb:30:in `perform'
[APSRJTW8ZX] [5::11 87] /opt/postal/lib/postal/worker.rb:53:in `receive_job'
[APSRJTW8ZX] [5::11 87] /opt/postal/lib/postal/worker.rb:84:in `block in join_queue'
[APSRJTW8ZX] [5::11 87] /opt/postal/vendor/bundle/ruby/2.4.0/gems/bunny-2.5.1/lib/bunny/consumer.rb:56:in `call'
[APSRJTW8ZX] [5::11 87] /opt/postal/vendor/bundle/ruby/2.4.0/gems/bunny-2.5.1/lib/bunny/channel.rb:1703:in `block in handle_frameset'
[APSRJTW8ZX] [5::11 87] /opt/postal/vendor/bundle/ruby/2.4.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:97:in `block (2 levels) in run_loop'
[APSRJTW8ZX] [5::11 87] /opt/postal/vendor/bundle/ruby/2.4.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:92:in `loop'
[APSRJTW8ZX] [5::11 87] /opt/postal/vendor/bundle/ruby/2.4.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:92:in `block in run_loop'
[APSRJTW8ZX] [5::11 87] /opt/postal/vendor/bundle/ruby/2.4.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:91:in `catch'
[APSRJTW8ZX] [5::11 87] /opt/postal/vendor/bundle/ruby/2.4.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:91:in `run_loop'
[APSRJTW8ZX] [5::11 87] Queued message was unlocked
[APSRJTW8ZX] Finished processing UnqueueMessageJob job in 0.064324046s

```

**Comment by mtahiue** [comment]
ok found my mistake
maximum_delivery_attempts: 18 
was missing in config file
