### ISSUE TITLE
Tracking Domains / 404 / The page you were looking for doesn't exist.

### ISSUE THREAD

**Issue by Widmo** [atech/postal#416]
Hi, i have configured tracing domains like in docs, 
postal convert link correctly ( fg: to https://click.domain.com/nqkmkr/m3oYLkuk )
and it pass me to postal page, but got 404. 

Log: 

```
==> log/rails.log <==
[web.1:191321] [2017-11-24T20:25:52.975] INFO -- : Started GET "/nqkmkr/m3oYLkuk" for _MY_IP_ at 2017-11-24 20:25:52 +0100
[web.1:191321] [2017-11-24T20:25:52.975] FATAL -- :
[web.1:191321] [2017-11-24T20:25:52.975] FATAL -- : ActionController::RoutingError (No route matches [GET] "/nqkmkr/m3oYLkuk"):
[web.1:191321] [2017-11-24T20:25:52.975] FATAL -- :
[web.1:191321] [2017-11-24T20:25:52.975] FATAL -- : actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
secure_headers (3.4.1) lib/secure_headers/middleware.rb:12:in `call'
sentry-raven (2.1.0) lib/raven/integrations/rack.rb:50:in `call'
railties (5.0.2) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/commonlogger.rb:38:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

How to debug it?

**Comment by willpower232** [comment]
How have you set up your click tracking?

**Comment by Widmo** [comment]
Like this: https://github.com/atech/postal/wiki/Click-&-Open-Tracking
Have server running, port open, domain forwarded. And got 404 with: 

```
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
If you are the application owner check the logs for more information.
```

**Comment by willpower232** [comment]
Can you send us the output of `sudo netstat -lnp` please?

**Comment by Widmo** [comment]
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      191321/[postal] web
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      2642/beam.smp
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      2640/mysqld
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      198613/systemd-reso
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      967/rpcbind
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1466/nginx: master
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      1738/epmd
tcp        0      0 W.A.N.99:5010       0.0.0.0:*               LISTEN      193448/[postal] fas
tcp        0      0 W.A.N.99:5011       0.0.0.0:*               LISTEN      193448/[postal] fas
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1834/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      2546/master
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1466/nginx: master
tcp        0      0 0.0.0.0:2812            0.0.0.0:*               LISTEN      7904/monit
tcp        0      0 0.0.0.0:5666            0.0.0.0:*               LISTEN      1964/nrpe
tcp6       0      0 :::5672                 :::*                    LISTEN      2642/beam.smp
tcp6       0      0 :::5355                 :::*                    LISTEN      198613/systemd-reso
tcp6       0      0 :::111                  :::*                    LISTEN      967/rpcbind
tcp6       0      0 :::80                   :::*                    LISTEN      1466/nginx: master
tcp6       0      0 :::4369                 :::*                    LISTEN      1738/epmd
tcp6       0      0 :::22                   :::*                    LISTEN      1834/sshd
tcp6       0      0 :::25                   :::*                    LISTEN      2546/master
tcp6       0      0 :::443                  :::*                    LISTEN      1466/nginx: master
tcp6       0      0 :::2812                 :::*                    LISTEN      7904/monit
tcp6       0      0 :::2525                 :::*                    LISTEN      193438/[postal] smt
tcp6       0      0 :::5666                 :::*                    LISTEN      1964/nrpe
udp        0      0 0.0.0.0:719             0.0.0.0:*                           967/rpcbind
udp        0      0 127.0.0.53:53           0.0.0.0:*                           198613/systemd-reso
udp        0      0 0.0.0.0:111             0.0.0.0:*                           967/rpcbind
udp        0      0 W.A.N2.7:123        0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N2.6:123        0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N2.5:123        0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.109:123       0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.108:123       0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.107:123       0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.106:123       0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.105:123       0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.104:123       0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.103:123       0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.102:123       0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.101:123       0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.100:123       0.0.0.0:*                           2100/ntpd
udp        0      0 W.A.N.99:123        0.0.0.0:*                           2100/ntpd
udp        0      0 192.168.1.170:123       0.0.0.0:*                           2100/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           2100/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           2100/ntpd
udp        0      0 0.0.0.0:5355            0.0.0.0:*                           198613/systemd-reso
udp6       0      0 :::719                  :::*                                967/rpcbind
udp6       0      0 :::111                  :::*                                967/rpcbind
udp6       0      0 ::1:123                 :::*                                2100/ntpd
udp6       0      0 :::123                  :::*                                2100/ntpd
udp6       0      0 :::5355                 :::*                                198613/systemd-reso
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     20490    1/systemd            /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     60075394 191315/[procodile]   /tmp/postal/pids/procodile.sock
unix  2      [ ACC ]     STREAM     LISTENING     20492    1/systemd            /run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     20494    1/systemd            /run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     LISTENING     24363    2546/master          private/tlsmgr
unix  2      [ ACC ]     STREAM     LISTENING     24366    2546/master          private/rewrite
unix  2      [ ACC ]     STREAM     LISTENING     19728    1162/VGAuthService   /var/run/vmware/guestServicePipe
unix  2      [ ACC ]     STREAM     LISTENING     24369    2546/master          private/bounce
unix  2      [ ACC ]     STREAM     LISTENING     24372    2546/master          private/defer
unix  2      [ ACC ]     STREAM     LISTENING     24375    2546/master          private/trace
unix  2      [ ACC ]     STREAM     LISTENING     24378    2546/master          private/verify
unix  2      [ ACC ]     STREAM     LISTENING     24384    2546/master          private/proxymap
unix  2      [ ACC ]     STREAM     LISTENING     24387    2546/master          private/proxywrite
unix  2      [ ACC ]     STREAM     LISTENING     24390    2546/master          private/smtp
unix  2      [ ACC ]     STREAM     LISTENING     24396    2546/master          private/relay
unix  2      [ ACC ]     STREAM     LISTENING     24402    2546/master          private/error
unix  2      [ ACC ]     STREAM     LISTENING     24405    2546/master          private/retry
unix  2      [ ACC ]     STREAM     LISTENING     24408    2546/master          private/discard
unix  2      [ ACC ]     STREAM     LISTENING     24411    2546/master          private/local
unix  2      [ ACC ]     STREAM     LISTENING     24414    2546/master          private/virtual
unix  2      [ ACC ]     STREAM     LISTENING     24417    2546/master          private/lmtp
unix  2      [ ACC ]     STREAM     LISTENING     24420    2546/master          private/anvil
unix  2      [ ACC ]     STREAM     LISTENING     24423    2546/master          private/scache
unix  2      [ ACC ]     STREAM     LISTENING     20511    1/systemd            /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     24426    2546/master          private/maildrop
unix  2      [ ACC ]     STREAM     LISTENING     24429    2546/master          private/uucp
unix  2      [ ACC ]     STREAM     LISTENING     24432    2546/master          private/ifmail
unix  2      [ ACC ]     STREAM     LISTENING     20514    1/systemd            /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     24435    2546/master          private/bsmtp
unix  2      [ ACC ]     STREAM     LISTENING     24438    2546/master          private/scalemail-backend
unix  2      [ ACC ]     STREAM     LISTENING     24441    2546/master          private/mailman
unix  2      [ ACC ]     STREAM     LISTENING     24352    2546/master          public/pickup
unix  2      [ ACC ]     STREAM     LISTENING     24356    2546/master          public/cleanup
unix  2      [ ACC ]     STREAM     LISTENING     24359    2546/master          public/qmgr
unix  2      [ ACC ]     STREAM     LISTENING     24381    2546/master          public/flush
unix  2      [ ACC ]     STREAM     LISTENING     24399    2546/master          public/showq
unix  2      [ ACC ]     STREAM     LISTENING     23461525 1/systemd            /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     1946     1/systemd            /run/systemd/journal/stdout
unix  2      [ ACC ]     SEQPACKET  LISTENING     1950     1/systemd            /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     1952     1/systemd            /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     1956     1/systemd            /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     20489    1/systemd            /var/lib/lxd/unix.socket
unix  2      [ ACC ]     STREAM     LISTENING     27562    3852/systemd         /run/user/0/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     1963     1/systemd            /run/rpcbind.sock
unix  2      [ ACC ]     STREAM     LISTENING     22441    1889/iscsid          @ISCSIADM_ABSTRACT_NAMESPACE
unix  2      [ ACC ]     STREAM     LISTENING     1984     1/systemd            /run/systemd/fsck.progress
unix  2      [ ACC ]     STREAM     LISTENING     20423    1735/python3         /var/run/fail2ban/fail2ban.sock
unix  2      [ ACC ]     STREAM     LISTENING     24527    2640/mysqld          /var/run/mysqld/mysqld.sock

```

**Comment by willpower232** [comment]
From what I can tell it looks like your click tracking links have ended up on the web interface instead of the click tracking server as the error logs are from puma.

Its interesting the click tracking is coming up on port 5010 and 5011, I didn't think it still did that. Do you have two IP addresses on your server? In order to use click tracking simply and easily, your nginx should be bound to one of them and click tracking the other so you see this in your `netstat`

![image](https://user-images.githubusercontent.com/1619102/33276523-b1276694-d38d-11e7-83cb-e400dd7abffc.png)

It might be that you haven't specified an IP address in your nginx server blocks so nginx gets in the way of whatever has been set up for click tracking so far.

**Comment by willpower232** [comment]
I've just remembered about switching off the 5010/5011, have a look here https://github.com/atech/postal/wiki/Abandoning-iptables

**Comment by Widmo** [comment]
Ok, so thank You for direction :) 

Tried to proxy it (at new IP, port 80 && 443) by nginx, but does not work. 

At least run fast_server at port 80 && 443 at another IP. It works. 

Thanks !
