### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by pyromaniackeca** [atech/postal#510]
Hello, I'm trying to set up a mailing server with postal. I have successfully installed it into a docker container and am able to access the web ui using a custom url via consul. After trying to log in. I consistently get:
`The change you wanted was rejected.`

Looking at the logs the error is:
```
12:10:21 web.1           | => [web.1:1600] [2018-02-27T12:10:21.898] INFO -- : Processing by SessionsController#create as HTML
12:10:21 web.1           | => [web.1:1600] [2018-02-27T12:10:21.899] INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"LWFjhqf3rzzMkEtvFPN9YTXugT6ChYfCOJWK+HNu5HyeIweMQUAjMCeTmaP+/WFW0KJxljtJ231tp0JI9vadYg==", "return_to"=>"", "email_address"=>"admin@qcontact.com", "password"=>"[FILTERED]", "commit"=>"Login"}
12:10:21 web.1           | => [web.1:1600] [2018-02-27T12:10:21.899] WARN -- : Can't verify CSRF token authenticity.
12:10:21 web.1           | => [web.1:1600] [2018-02-27T12:10:21.900] INFO -- : Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)
12:10:21 web.1           | => [web.1:1600] [2018-02-27T12:10:21.901] FATAL -- :   
12:10:21 web.1           | => [web.1:1600] [2018-02-27T12:10:21.901] FATAL -- : ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
12:10:21 web.1           | => [web.1:1600] [2018-02-27T12:10:21.901] FATAL -- :   
12:10:21 web.1           | => [web.1:1600] [2018-02-27T12:10:21.901] FATAL -- : actionpack (5.0.2) lib/action_controller/metal/request_forgery_protection.rb:195:in `handle_unverified_request'
```
I tried to do some research and fix it myself, but I was unable to. From what I could gather the problem seems to come from the nginx configuration.

Thank you.

**Comment by willpower232** [comment]
I probably don't know enough about docker and consul but I would imagine that there is something involved under the hood which means the CSRF token is invalid by the time you are trying to use it.

You may be interested in https://github.com/atech/postal/issues/158

**Comment by pyromaniackeca** [comment]
Thank you for the assistance, I've opted to turn off csrf protection for now. The application isn't live yet, so it's not too big a deal, hopefully I will figure something out until then.

P.S.
Cool name.

**Comment by jackrobson** [comment]
I had this same issue. Turns out it was something todo with my Chrome browser.

Sometimes websites (i.e. YouTube, Facebook, Github) stop working or give errors when I use Chrome.

A computer restart or switching browsers works.

**Comment by gonace** [comment]
I'm getting this error with the "simple setup" tried 3 times with 3 new instances of a virtual machine, but always end up here

```
23:27:01 web.1              | => [web.1:14785] [2019-08-16T23:27:01.879] INFO -- : Started POST "/login" for *.*.*.* at 2019-08-16 23:27:01 +0200
23:27:01 web.1              | => [web.1:14785] [2019-08-16T23:27:01.880] INFO -- : Processing by SessionsController#create as HTML
23:27:01 web.1              | => [web.1:14785] [2019-08-16T23:27:01.880] INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"QqSiIZrenik6WtBWMcNi18apDkrBCtqUOyfYzrgOZsqHh/lDygmqtBFM5j9MCuc2RwEGPbdhgB6yB/AR4sQ7YQ==", "return_to"=>"", "email_address"=>"***.***@***.**", "password"=>"[FILTERED]", "commit"=>"Login"}
23:27:01 web.1              | => [web.1:14785] [2019-08-16T23:27:01.883] WARN -- : Can't verify CSRF token authenticity.
23:27:01 web.1              | => [web.1:14785] [2019-08-16T23:27:01.883] INFO -- : Completed 422 Unprocessable Entity in 3ms (ActiveRecord: 0.4ms)
23:27:01 web.1              | => [web.1:14785] [2019-08-16T23:27:01.884] FATAL -- :
23:27:01 web.1              | => [web.1:14785] [2019-08-16T23:27:01.884] FATAL -- : ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
23:27:01 web.1              | => [web.1:14785] [2019-08-16T23:27:01.885] FATAL -- :
23:27:01 web.1              | => [web.1:14785] [2019-08-16T23:27:01.885] FATAL -- : actionpack (5.2.2.1) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:426:in `block in make_lambda'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:199:in `block in halting'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:513:in `block in invoke_before'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:513:in `each'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:513:in `invoke_before'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:107:in `block in run_callbacks'
23:27:01 web.1              | => sentry-raven (2.7.4) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:118:in `instance_exec'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:136:in `run_callbacks'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/notifications.rb:168:in `instrument'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
23:27:01 web.1              | => activerecord (5.2.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/abstract_controller/base.rb:134:in `process'
23:27:01 web.1              | => actionview (5.2.2.1) lib/action_view/rendering.rb:32:in `process'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_controller/metal.rb:191:in `dispatch'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_controller/metal.rb:252:in `dispatch'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
23:27:01 web.1              | => moonrope (2.0.1) lib/moonrope/rack_middleware.rb:101:in `call'
23:27:01 web.1              | => moonrope (2.0.1) lib/moonrope/doc_server.rb:118:in `call'
23:27:01 web.1              | => rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
23:27:01 web.1              | => rack (2.0.6) lib/rack/etag.rb:25:in `call'
23:27:01 web.1              | => rack (2.0.6) lib/rack/conditional_get.rb:38:in `call'
23:27:01 web.1              | => rack (2.0.6) lib/rack/head.rb:12:in `call'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
23:27:01 web.1              | => rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
23:27:01 web.1              | => rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
23:27:01 web.1              | => railties (5.2.2.1) lib/rails/rack/logger.rb:38:in `call_app'
23:27:01 web.1              | => railties (5.2.2.1) lib/rails/rack/logger.rb:28:in `call'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
23:27:01 web.1              | => rack (2.0.6) lib/rack/method_override.rb:22:in `call'
23:27:01 web.1              | => rack (2.0.6) lib/rack/runtime.rb:22:in `call'
23:27:01 web.1              | => activesupport (5.2.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
23:27:01 web.1              | => actionpack (5.2.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
23:27:01 web.1              | => rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
23:27:01 web.1              | => secure_headers (6.0.0) lib/secure_headers/middleware.rb:13:in `call'
23:27:01 web.1              | => sentry-raven (2.7.4) lib/raven/integrations/rack.rb:51:in `call'
23:27:01 web.1              | => railties (5.2.2.1) lib/rails/engine.rb:524:in `call'
23:27:01 web.1              | => puma (3.12.0) lib/puma/commonlogger.rb:38:in `call'
23:27:01 web.1              | => puma (3.12.0) lib/puma/configuration.rb:225:in `call'
23:27:01 web.1              | => puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
23:27:01 web.1              | => puma (3.12.0) lib/puma/server.rb:472:in `process_client'
23:27:01 web.1              | => puma (3.12.0) lib/puma/server.rb:332:in `block in run'
23:27:01 web.1              | => puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by acsfer** [comment]
I was having this problem with nginx configured with:

`add_header Referrer-Policy "no-referrer" always;`

after changing it to

`add_header Referrer-Policy "same-origin" always;`

i can login/logout again.

**Comment by willpower232** [comment]
@acsfer FWIW, it seems ruby on rails has relied on referrers for some time https://github.com/rails/rails/commit/428939be9f954d39b0c41bc53d85d0d106b9d1a1

**Comment by juniorcines** [comment]
For anyone still having this problem, I added this to nginx proxy reverse and it worked for me.

```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
```
