### ISSUE TITLE
Mysql2::Error: Incorrect string value: '\xF0\x9F\x99\x8B"' for column 'subject' at row 1

### ISSUE THREAD

**Issue by rbustos** [atech/postal#588]
Hi,

This message happens when we try to add emojis in the subject.

_> ==> /opt/postal/log/smtp_server.log <==
> [smtp.1:36816] [2018-05-15T14:54:14.038] ERROR -- : [AWQTLK] An error occurred while processing data from a client.
> [smtp.1:36816] [2018-05-15T14:54:14.038] ERROR -- : [AWQTLK] Mysql2::Error: Incorrect string value: '\xF0\x9F\x99\x8B"' for column 'subject' at row 1
> [smtp.1:36816] [2018-05-15T14:54:14.038] ERROR -- : [AWQTLK] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
> [smtp.1:36816] [2018-05-15T14:54:14.038] ERROR -- : [AWQTLK] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
> [smtp.1:36816] [2018-05-15T14:54:14.038] ERROR -- : [AWQTLK] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
> [smtp.1:36816] [2018-05-15T14:54:14.039] ERROR -- : [AWQTLK] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
> [smtp.1:36816] [2018-05-15T14:54:14.039] ERROR -- : [AWQTLK] /opt/postal/app/lib/postal/message_db/database.rb:319:in `query_on_connection'
> [smtp.1:36816] [2018-05-15T14:54:14.039] ERROR -- : [AWQTLK] /opt/postal/app/lib/postal/message_db/database.rb:224:in `block in insert'
> [smtp.1:36816] [2018-05-15T14:54:14.039] ERROR -- : [AWQTLK] /opt/postal/app/lib/postal/message_db/mysql.rb:20:in `client'
> [smtp.1:36816] [2018-05-15T14:54:14.039] ERROR -- : [AWQTLK] /opt/postal/app/lib/postal/message_db/database.rb:342:in `with_mysql'
> [smtp.1:36816] [2018-05-15T14:54:14.040] ERROR -- : [AWQTLK] /opt/postal/app/lib/postal/message_db/database.rb:223:in `insert'
> [smtp.1:36816] [2018-05-15T14:54:14.040] ERROR -- : [AWQTLK] /opt/postal/app/lib/postal/message_db/message.rb:561:in `_create'
> [smtp.1:36816] [2018-05-15T14:54:14.040] ERROR -- : [AWQTLK] /opt/postal/app/lib/postal/message_db/message.rb:206:in `save'
> [smtp.1:36816] [2018-05-15T14:54:14.040] ERROR -- : [AWQTLK] /opt/postal/app/lib/postal/smtp_server/client.rb:410:in `block in finished'_

Postal Version: 1.0.0-67d0f6514d-stable

We tried with : "ALTER TABLE messages CHANGE subject subject VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;" with no luck.

**Comment by rbustos** [comment]
Solved in : #391
