### ISSUE TITLE
Postal Broken

### ISSUE THREAD

**Issue by lokival** [atech/postal#670]
Trying to troubleshoot a broken postal install, gives the following output on postal run -

10:51:41 system          | Procodile supervisor started with PID 53407
10:51:41 system          | Application root is /opt/postal/app
10:51:41 system          | Automatic respawning is disabled
10:51:41 control         | Listening at /tmp/postal/pids/procodile.sock
10:51:41 system          | Reloading configuration
10:51:41 web.1           | Started with PID 53411
10:51:41 worker.1        | Started with PID 53413
10:51:41 cron.1          | Started with PID 53416
10:51:41 smtp.1          | Started with PID 53418
10:51:41 requeuer.1      | Started with PID 53422
10:51:42 web.1           | => Puma starting in single mode...
10:51:42 web.1           | => * Version 3.11.2 (ruby 2.3.7-p456), codename: Love Song
10:51:42 web.1           | => * Min threads: 5, max threads: 5
10:51:42 web.1           | => * Environment: production
10:51:46 cron.1          | => rake aborted!
10:51:46 cron.1          | => TypeError: no implicit conversion of true into String
10:51:46 cron.1          | => /opt/postal/app/config/application.rb:13:in `<top (required)>'
10:51:46 cron.1          | => /opt/postal/app/Rakefile:4:in `require_relative'
10:51:46 cron.1          | => /opt/postal/app/Rakefile:4:in `<top (required)>'
10:51:46 cron.1          | => /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
10:51:46 cron.1          | => (See full trace by running task with --trace)
10:51:46 web.1           | => ! Unable to load application: TypeError: no implicit conversion of true into String
10:51:46 web.1           | => /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `require': no implicit conversion of true into String (TypeError)
10:51:46 web.1           | =>   from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `block (2 levels) in require'
10:51:46 web.1           | =>   from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `each'
10:51:46 web.1           | =>   from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `block in require'
10:51:46 web.1           | =>   from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `each'
10:51:46 web.1           | =>   from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `require'
10:51:46 web.1           | =>   from /usr/lib/ruby/vendor_ruby/bundler.rb:132:in `require'
10:51:46 web.1           | =>   from /opt/postal/app/config/application.rb:13:in `<top (required)>'
10:51:46 web.1           | =>   from /opt/postal/app/config/environment.rb:2:in `require_relative'
10:51:46 web.1           | =>   from /opt/postal/app/config/environment.rb:2:in `<top (required)>'
10:51:46 web.1           | =>   from config.ru:3:in `require_relative'
10:51:46 web.1           | =>   from config.ru:3:in `block in <main>'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
10:51:46 web.1           | =>   from config.ru:in `new'
10:51:46 web.1           | =>   from config.ru:in `<main>'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/configuration.rb:318:in `load_rackup'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/configuration.rb:243:in `app'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/runner.rb:138:in `load_and_bind'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/single.rb:87:in `run'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/launcher.rb:183:in `run'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/cli.rb:77:in `run'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/bin/puma:10:in `<top (required)>'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/bin/puma:22:in `load'
10:51:46 web.1           | =>   from /opt/postal/app/vendor/bundle/ruby/2.3.0/bin/puma:22:in `<main>'
10:51:46 worker.1        | => /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `require': no implicit conversion of true into String (TypeError)
10:51:46 worker.1        | =>   from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `block (2 levels) in require'
10:51:46 worker.1        | =>   from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `each'
10:51:46 worker.1        | =>   from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `block in require'
10:51:46 worker.1        | =>   from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `each'
10:51:46 worker.1        | =>   from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `require'
10:51:46 worker.1        | =>   from /usr/lib/ruby/vendor_ruby/bundler.rb:132:in `require'
10:51:46 worker.1        | =>   from /opt/postal/app/config/application.rb:13:in `<top (required)>'
10:51:46 worker.1        | =>   from /opt/postal/app/config/environment.rb:2:in `require_relative'
10:51:46 worker.1        | =>   from /opt/postal/app/config/environment.rb:2:in `<top (required)>'
10:51:46 worker.1        | =>   from script/worker.rb:2:in `require_relative'
10:51:46 worker.1        | =>   from script/worker.rb:2:in `<main>'
10:51:46 requeuer.1      | => rake aborted!
10:51:46 requeuer.1      | => TypeError: no implicit conversion of true into String
10:51:46 requeuer.1      | => /opt/postal/app/config/application.rb:13:in `<top (required)>'
10:51:46 requeuer.1      | => /opt/postal/app/Rakefile:4:in `require_relative'
10:51:46 requeuer.1      | => /opt/postal/app/Rakefile:4:in `<top (required)>'
10:51:46 requeuer.1      | => /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
10:51:46 requeuer.1      | => (See full trace by running task with --trace)
10:51:46 smtp.1          | => rake aborted!
10:51:46 smtp.1          | => TypeError: no implicit conversion of true into String
10:51:46 smtp.1          | => /opt/postal/app/config/application.rb:13:in `<top (required)>'
10:51:46 smtp.1          | => /opt/postal/app/Rakefile:4:in `require_relative'
10:51:46 smtp.1          | => /opt/postal/app/Rakefile:4:in `<top (required)>'
10:51:46 smtp.1          | => /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
10:51:46 smtp.1          | => (See full trace by running task with --trace)
10:51:47 web.1           | Process has stopped. Respawning not available.
10:51:47 web.1           | Removed PID file
10:51:47 worker.1        | Process has stopped. Respawning not available.
10:51:47 worker.1        | Removed PID file
10:51:47 cron.1          | Process has stopped. Respawning not available.
10:51:47 cron.1          | Removed PID file
10:51:47 smtp.1          | Process has stopped. Respawning not available.
10:51:47 smtp.1          | Removed PID file
10:51:47 requeuer.1      | Process has stopped. Respawning not available.
10:51:47 requeuer.1      | Removed PID file
10:51:47 system          | All processes have stopped
10:51:47 system          | Stopping Procodile supervisor

**Comment by lokival** [comment]
Update,

Fixed this by removing and re-installing ruby
