### ISSUE TITLE
Postal started suddenly crashing

### ISSUE THREAD

**Issue by ajarmoszuk** [atech/postal#691]
I'm getting the following error in the log when it's being run with `postal run` (note that no changes have been made to the server since June)

```
00:35:34 system          | Procodile supervisor started with PID 23183
00:35:34 system          | Application root is /opt/postal/app
00:35:34 system          | Automatic respawning is disabled
00:35:34 system          | Reloading configuration
00:35:34 web.1           | Started with PID 23187
00:35:34 fast.1          | Started with PID 23189
00:35:34 worker.1        | Started with PID 23191
00:35:34 cron.1          | Started with PID 23193
00:35:34 control         | Listening at /tmp/postal/pids/procodile.sock
00:35:34 smtp.1          | Started with PID 23195
00:35:34 requeuer.1      | Started with PID 23197
00:35:37 web.1           | => Puma starting in single mode...
00:35:37 web.1           | => * Version 3.8.2 (ruby 2.3.7-p456), codename: Sassy Salamander
00:35:37 web.1           | => * Min threads: 5, max threads: 5
00:35:37 web.1           | => * Environment: production
00:35:49 requeuer.1      | => [requeuer.1:23197] [2018-11-01T00:35:49.566] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
00:35:49 cron.1          | => [cron.1:23193] [2018-11-01T00:35:49.595] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
00:35:49 fast.1          | => [fast.1:23189] [2018-11-01T00:35:49.685] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
00:35:49 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:49.689] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
00:35:50 cron.1          | => [cron.1:23193] [2018-11-01T00:35:50.422] INFO -- : Starting clock for 8 events: [ every-1-minutes every-15-minutes every-15-minutes every-15-minutes every-15-minutes every-hour every-hour every-day ]
00:35:50 requeuer.1      | => [requeuer.1:23197] [2018-11-01T00:35:50.427] INFO -- : Running message requeuer...
00:35:50 cron.1          | => [cron.1:23193] [2018-11-01T00:35:50.435] INFO -- : Triggering 'every-1-minutes'
00:35:50 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:50.546] INFO -- : Listening on port 25
00:35:51 fast.1          | => [fast.1:23189] [2018-11-01T00:35:51.422] INFO -- : Fast server started listening on HTTP (149.202.154.100:80)
00:35:51 fast.1          | => [fast.1:23189] [2018-11-01T00:35:51.439] INFO -- : Fast server started listening on HTTPS port (149.202.154.100:443)
00:35:51 worker.1        | => [worker.1:23191] [2018-11-01T00:35:51.764] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
00:35:51 web.1           | => [web.1:23187] [2018-11-01T00:35:51.801] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.044] INFO -- : Worker running with 4 threads
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.057] INFO -- : [ROTFBHIKEN] Started processing RequeueWebhooksJob job
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.057] INFO -- : Joined main queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.057] INFO -- : [XDUZYTHVDN] Started processing SendNotificationsJob job
00:35:52 web.1           | => * Listening on tcp://127.0.0.1:5000
00:35:52 web.1           | => Use Ctrl-C to stop
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.215] INFO -- : [XDUZYTHVDN] Finished processing SendNotificationsJob job in 0.157277899s
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.218] INFO -- : [ROTFBHIKEN] Finished processing RequeueWebhooksJob job in 0.160990888s
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.240] INFO -- : Joined outgoing-1 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.241] INFO -- : Joined outgoing-2 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.243] INFO -- : Joined outgoing-3 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.244] INFO -- : Joined outgoing-4 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.246] INFO -- : Joined outgoing-5 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.247] INFO -- : Joined outgoing-6 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.248] INFO -- : Joined outgoing-7 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.250] INFO -- : Joined outgoing-8 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.251] INFO -- : Joined outgoing-9 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.252] INFO -- : Joined outgoing-10 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.254] INFO -- : Joined outgoing-11 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.255] INFO -- : Joined outgoing-12 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.256] INFO -- : Joined outgoing-13 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.258] INFO -- : Joined outgoing-14 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.259] INFO -- : Joined outgoing-15 queue
00:35:52 worker.1        | => [worker.1:23191] [2018-11-01T00:35:52.260] INFO -- : Joined outgoing-16 queue
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.324] DEBUG -- : [TIKQOX]    Connection opened from ::ffff:185.36.81.87
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.324] DEBUG -- : [TIKQOX]    Client identified as ::ffff:185.36.81.87
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.446] DEBUG -- : [TIKQOX] <= EHLO 51.38.227.174
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.460] DEBUG -- : [TIKQOX] => 250-My capabilities are
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.461] DEBUG -- : [TIKQOX] => 250-STARTTLS
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.461] DEBUG -- : [TIKQOX] => 250 AUTH CRAM-MD5 PLAIN LOGIN
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.659] DEBUG -- : [TIKQOX] <= AUTH LOGIN
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.660] DEBUG -- : [TIKQOX] => 334 VXNlcm5hbWU6
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.688] DEBUG -- : [TIKQOX] <= c29sYXI=
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.688] DEBUG -- : [TIKQOX] => 334 UGFzc3dvcmQ6
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.716] DEBUG -- : [TIKQOX] <= MTExMTEx
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.937] DEBUG -- : [TIKQOX] => 535 Invalid credential
00:35:55 smtp.1          | => [smtp.1:23195] [2018-11-01T00:35:55.972] DEBUG -- : [TIKQOX]    Connection closed
00:36:03 system          | Reloading configuration
00:36:03 system          | Reloading configuration
00:36:03 system          | Stopping all Postal processes
00:36:03 web.1           | Sending TERM to 23187
00:36:03 web.1           | => - Gracefully stopping, waiting for requests to finish
00:36:03 web.1           | => === puma shutdown: 2018-11-01 00:36:03 +0000 ===
00:36:03 web.1           | => - Goodbye!
00:36:03 fast.1          | Sending TERM to 23189
00:36:03 fast.1          | => rake aborted!
00:36:03 fast.1          | => SignalException: SIGTERM
00:36:03 fast.1          | => /opt/postal/app/lib/postal/fast_server/server.rb:29:in `select'
00:36:03 fast.1          | => /opt/postal/app/lib/postal/fast_server/server.rb:29:in `block in run'
00:36:03 fast.1          | => /opt/postal/app/lib/postal/fast_server/server.rb:27:in `loop'
00:36:03 fast.1          | => /opt/postal/app/lib/postal/fast_server/server.rb:27:in `run'
00:36:03 fast.1          | => /opt/postal/app/lib/tasks/postal.rake:33:in `block (2 levels) in <top (required)>'
00:36:03 fast.1          | => /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
00:36:03 fast.1          | => Tasks: TOP => postal:fast_server
00:36:03 fast.1          | => (See full trace by running task with --trace)
00:36:03 worker.1        | Sending TERM to 23191
00:36:03 cron.1          | Sending TERM to 23193
00:36:03 smtp.1          | Sending TERM to 23195
00:36:03 cron.1          | => Exiting...
00:36:03 smtp.1          | => Received TERM signal, shutting down.
00:36:03 requeuer.1      | Sending TERM to 23197
00:36:04 web.1           | Removed PID file
00:36:04 fast.1          | Removed PID file
00:36:04 cron.1          | Removed PID file
00:36:04 smtp.1          | Removed PID file
00:36:04 requeuer.1      | Removed PID file
00:36:04 worker.1        | => [worker.1:23191] [2018-11-01T00:36:04.266] INFO -- : Exiting immediately because no jobs running
00:36:07 worker.1        | Removed PID file
00:36:07 system          | All processes have stopped
00:36:07 system          | Stopping Procodile supervisor

```

**Comment by willpower232** [comment]
Is there any reason you're watching `postal run`, do you get better results with `postal start`?

**Comment by ajarmoszuk** [comment]
No, with postal start and tailing the whole log folder I get no errors and it keeps restarting every couple of minutes by its own.

**Comment by willpower232** [comment]
Have you monitored your servers available memory and CPU to see if they're being maxed out at any point? Is there anything else running on your server which would be stopping the processes externally?

**Comment by ajarmoszuk** [comment]
Yes, it seems that the process was crashing because the CPU and memory were being maxed out, it has now been resolved. Thanks for help.
