### ISSUE TITLE
Filter chain halted as :login_required rendered or redirected

### ISSUE THREAD

**Issue by ilyacherevkov** [atech/postal#703]
When accessing web-interface with admin email / password, I'm facing error in rails.log
Also, latest version of Haml doesn't work for me. I needed to specify version 5.0.4 explicitly.

 ```
 Started GET "/login?return_to=%2F" for xxx.xxx.xxx.xxx at 2018-11-29 07:42:11 +0000
 Processing by SessionsController#new as HTML
   Parameters: {"return_to"=>"/"}
   Rendering sessions/new.html.haml within layouts/sub
   Rendered sessions/new.html.haml within layouts/sub (1.2ms)
 Completed 200 OK in 3ms (Views: 2.8ms | ActiveRecord: 0.0ms)
 Started GET "/" for xxx.xxx.xxx.xxx at 2018-11-29 07:42:12 +0000
 Processing by OrganizationsController#index as HTML
 Redirected to https://domain.com/login?return_to=%2F
 Filter chain halted as :login_required rendered or redirected
 Completed 302 Found in 1ms (ActiveRecord: 0.0ms)
 Started GET "/login?return_to=%2F" for xxx.xxx.xxx.xxx at 2018-11-29 07:42:12 +0000
 Processing by SessionsController#new as HTML
   Parameters: {"return_to"=>"/"}
   Rendering sessions/new.html.haml within layouts/sub
   Rendered sessions/new.html.haml within layouts/sub (1.2ms)
 Completed 200 OK in 3ms (Views: 2.5ms | ActiveRecord: 0.0ms)
 Started GET "/" for xxx.xxx.xxx.xxx at 2018-11-29 07:42:12 +0000
 Processing by OrganizationsController#index as HTML
 Redirected to https://domain.com/login?return_to=%2F
 Filter chain halted as :login_required rendered or redirected
 Completed 302 Found in 1ms (ActiveRecord: 0.0ms)
 Started GET "/login?return_to=%2F" for xxx.xxx.xxx.xxx at 2018-11-29 07:42:12 +0000
 Processing by SessionsController#new as HTML
   Parameters: {"return_to"=>"/"}
   Rendering sessions/new.html.haml within layouts/sub
   Rendered sessions/new.html.haml within layouts/sub (1.2ms)
 Completed 200 OK in 3ms (Views: 2.4ms | ActiveRecord: 0.0ms)
 Started POST "/login" for xxx.xxx.xxx.xxx at 2018-11-29 07:42:19 +0000
 Processing by SessionsController#create as HTML
   Parameters: {"utf8"=>"✓", "authenticity_token"=>"XXXXX", "return_to"=>"/", "email_address"=>"email.com", "password"=>"[FILTERED]", "commit"=>"Login"}
 Completed 500 Internal Server Error in 103ms (ActiveRecord: 0.4ms)
 NoMethodError (undefined method `host=' for #<Authie::Session:0x00007fcc5415a3b0>):
 app/controllers/application_controller.rb:127:in `login'
app/controllers/sessions_controller.rb:9:in `create'
```

**Comment by ilyacherevkov** [comment]
Idk what happened, but fresh installation with ruby2.3 worked (used ruby 2.5 previously).

**Comment by willpower232** [comment]
Thanks for letting us know, I think there are a few Ruby 2.5 related issues floating around.
