### ISSUE TITLE
Error 530 From/Sender name is not valid

### ISSUE THREAD

**Issue by trod90** [atech/postal#728]
Hello, 

I having this error when trying to send a mail using *smtplib*  from python.

`smtplib.SMTPDataError: (530, b'From/Sender name is not valid')`

I've configured the dns records, the postal.yml and the domain config for the organization.

![image](https://user-images.githubusercontent.com/46900267/51488355-15ca9f80-1d84-11e9-847d-a2f0c72ee096.png)
 
![image](https://user-images.githubusercontent.com/46900267/51488387-30047d80-1d84-11e9-8b9c-d07a1d4e9a9a.png)

![image](https://user-images.githubusercontent.com/46900267/51488426-4c081f00-1d84-11e9-8004-fca9826ee444.png)

DNS Records
![image](https://user-images.githubusercontent.com/46900267/51488626-cf297500-1d84-11e9-803f-97ee16b4ca3d.png)

I have been trying different configurations with the records and the organization's domain (via webui) with no success. Seems that I'm missing something.

If anyone knows whats the problem I would really appreciate it.

Regards.

**Comment by trod90** [comment]
Oh, I see.

I've changed to the info that appears here with no luck:
![image](https://user-images.githubusercontent.com/46900267/51536801-837dd680-1e2b-11e9-8f15-844aff6c79f3.png)

I tried with <organization_name>/mzzo-postal and <organization_name>/test-server but i get the same error.

My test script:
![image](https://user-images.githubusercontent.com/46900267/51537398-2edb5b00-1e2d-11e9-8719-0db21c3f9c6a.png)

**Comment by trod90** [comment]
Yes, I've tried configuring the domain in the *mail server > domains* and *organization > domains* sections. I don't know where should be configured, actually, couldn't find information about that.

Here is my Domain config at the "Organization > Domains":
![image](https://user-images.githubusercontent.com/46900267/51539594-25ed8800-1e33-11e9-8ef2-fe6b529f9aaf.png)

**Comment by willpower232** [comment]
Okay this is a bit of a guess as I don't know python that well but you're using

```python
mail_from = ("postal@internal.mzzo.com")
```

whereas the [documentation for Sender ](https://sender.readthedocs.io/)suggests either

```python
mail_from = "postal@internal.mzzo.com"
```

or

```python
mail_from = ("trod90", "postal@internal.mzzo.com")
```

should be used instead.

**Comment by trod90** [comment]
Tried that:
![image](https://user-images.githubusercontent.com/46900267/51558770-1126e980-1e5f-11e9-9dab-6d3bb962432e.png)

And this is the debug I get:
```
send: 'ehlo [192.168.100.52]\r\n'
reply: b'250-My capabilities are\r\n'
reply: b'250 AUTH CRAM-MD5 PLAIN LOGIN\r\n'
reply: retcode (250); Msg: b'My capabilities are\nAUTH CRAM-MD5 PLAIN LOGIN'
send: 'AUTH CRAM-MD5\r\n'
reply: b'334 PDNhYzhiMTg1MmY3ZGY5OTdjOTc1QG1haWwuaW50ZXJuYWwubXp6by5jb20+\r\n'
reply: retcode (334); Msg: b'PDNhYzhiMTg1MmY3ZGY5OTdjOTc1QG1haWwuaW50ZXJuYWwubXp6by5jb20+'
send: 'bXp6by9tenpvLXBvc3RhbCAyMzY3NTJkOWM4MDBjNDBhNmM5MzdiYWE3OWQ5M2EwNw==\r\n'
reply: b'535 Denied\r\n'
reply: retcode (535); Msg: b'Denied'
send: 'AUTH PLAIN AG16em8vbXp6by1wb3N0YWwAd0hhWFUwRWxObmhzMmFJS3NtRXc5T0xF\r\n'
reply: b'235 Granted for mzzo/test-server\r\n'
reply: retcode (235); Msg: b'Granted for mzzo/test-server'
send: 'mail FROM:<postal@internal.mzzo.com>\r\n'
reply: b'250 OK\r\n'
reply: retcode (250); Msg: b'OK'
send: 'rcpt TO:<windlaze@gmail.com>\r\n'
reply: b'250 OK\r\n'
reply: retcode (250); Msg: b'OK'
send: 'data\r\n'
reply: b'354 Go ahead\r\n'
reply: retcode (354); Msg: b'Go ahead'
data: (354, b'Go ahead')
send: b'Content-Type: multipart/mixed; boundary="===============8649352757931087811=="\nMIME-Version: 1.0\nSubject: =?utf-8?q?Postal_test_subject?=\nFrom: =?utf-8?q?trod90?= <postal@internal.mzzo.com>\nTo: windlaze@gmail.com\nDate: Tue, 22 Jan 2019 15:56:44 -0300\nMessage-ID: <154818340249.31438.14387079228784665554@notebook-mzzo>\n\n--===============8649352757931087811==\nContent-Type: multipart/alternative; boundary="===============8333879903319834932=="\nMIME-Version: 1.0\n\n--===============8333879903319834932==\nContent-Type: text/plain; charset="utf-8"\nMIME-Version: 1.0\nContent-Transfer-Encoding: 7bit\n\n\n--===============8333879903319834932==\nContent-Type: text/html; charset="utf-8"\nMIME-Version: 1.0\nContent-Transfer-Encoding: 7bit\n\nPostal test message...\n--===============8333879903319834932==--\n\n--===============8649352757931087811==--\n\r\n.\r\n'
reply: b'530 From/Sender name is not valid\r\n'
reply: retcode (530); Msg: b'From/Sender name is not valid'
data: (530, b'From/Sender name is not valid')
send: 'rset\r\n'
reply: b'250 OK\r\n'
reply: retcode (250); Msg: b'OK'
send: 'quit\r\n'
reply: b'221 Closing Connection\r\n'
reply: retcode (221); Msg: b'Closing Connection'
Traceback (most recent call last):
  File "mailsend.py", line 16, in <module>
    mail.send(msg)
  File "/home/trodriguez/.local/lib/python3.6/site-packages/sender.py", line 97, in send
    c.send(message)
  File "/home/trodriguez/.local/lib/python3.6/site-packages/sender.py", line 148, in send
    message.mail_options, message.rcpt_options)
  File "/usr/lib/python3.6/smtplib.py", line 888, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (530, b'From/Sender name is not valid')
```

Seems that it's not working either.

**Comment by willpower232** [comment]
Based on your screenshot, the `test-server` credential will have access to the internal.mzzo.com domain but `mzzo-postal` isn't in your screenshot so presumably does not have access to that domain unless you've set it up twice.

It also looks like Sender tries CRAM-MD5 first so it would be useful to double check the username. Follow the steps on https://github.com/atech/postal/issues/414#issuecomment-401848161 and see if you can get the right username for that password.

**Comment by trod90** [comment]
Yeah, right now I changed those credentials to test and it didn't work. 

![image](https://user-images.githubusercontent.com/46900267/51614018-8cda7200-1f03-11e9-91f7-1609ddd49536.png)
![image](https://user-images.githubusercontent.com/46900267/51614111-c317f180-1f03-11e9-8f5e-2b4695bd34d4.png)

Same error:
```
smtplib.SMTPDataError: (530, b'From/Sender name is not valid')
```

Also, I've done a little debugging on the **find_authenticated_domain_from_headers** method of the server:
 
```
  def find_authenticated_domain_from_headers(headers)
          logger = Logger.new(STDOUT)
          logger = Logger.new('logfile.log')
    header_to_check = ['from']
    header_to_check << 'sender' if self.allow_sender?
    header_to_check.each do |header_name|
      if headers[header_name].is_a?(Array)
        values = headers[header_name]
      else
        values = [headers[header_name].to_s]
      end
      logger.debug "headers: #{headers}"
      logger.debug "values: #{values}"
      logger.debug "header_name: #{header_name}"
      authenticated_domains = values.map { |v| authenticated_domain_for_address(v) }.compact
      logger.debug "authenticated_domains: #{authenticated_domains}"
      if authenticated_domains.size == values.size
        return authenticated_domains.first
      end
    end
    nil
  end
```

This is the output for the printed variables from the **logfile.log**:
```
D, [2019-01-23T11:40:46.129907 #10340] DEBUG -- : headers: {"received"=>["from [192.168.100.52] (::ffff:186.103.239.190 [::ffff:186.103.239.190]) by internal.mzzo.com with SMTP; Wed, 23 Jan 2019 11:40:46 -0300"]}
D, [2019-01-23T11:40:46.129983 #10340] DEBUG -- : values: [""]
D, [2019-01-23T11:40:46.130018 #10340] DEBUG -- : header_name: from
D, [2019-01-23T11:40:46.130084 #10340] DEBUG -- : authenticated_domains: []
D, [2019-01-23T11:40:46.130167 #10340] DEBUG -- : headers: {"received"=>["from [192.168.100.52] (::ffff:186.103.239.190 [::ffff:186.103.239.190]) by internal.mzzo.com with SMTP; Wed, 23 Jan 2019 11:40:46 -0300"]}
D, [2019-01-23T11:40:46.130221 #10340] DEBUG -- : values: [""]
D, [2019-01-23T11:40:46.130257 #10340] DEBUG -- : header_name: sender
D, [2019-01-23T11:40:46.130304 #10340] DEBUG -- : authenticated_domains: []
```

I don't know the reason why the **values** variable is empty before the method **authenticated_domain_for_address** is called.

**Comment by willpower232** [comment]
Your debugging shows that the sender header is present.

I think that by default, this is disabled for security reasons. In the Advanced Settings for the organisation, you should see an option about allowing the sender header. Try changing that and see if that helps.

Unfortunately its not clear from the documentation whether that header can be removed or is just always used by default.

**Comment by trod90** [comment]
Ok. I don't know if this is the option you mentioned:
![image](https://user-images.githubusercontent.com/46900267/51632033-12264c80-1f2d-11e9-9c30-6abf36780f52.png)
![image](https://user-images.githubusercontent.com/46900267/51632073-2e29ee00-1f2d-11e9-8080-912a81c2dec5.png)

Just tried with that enabled and the error is the same.

**Comment by willpower232** [comment]
Have you tried without the brackets and name field?  i.e.

```python
mail_from = "postal@internal.mzzo.com"
```

**Comment by vishnus** [comment]
Hi @willpower232 

We also encountered a similar issue, but not every all systems. Some python smtp lib programs, and recently https://bigbluebutton.org/ 's SMTP test mails are unable to send mails through postal and it gives same error:
```
[KPBLOQ]    Connection opened from ::ffff:192.168.1.126
[KPBLOQ]    Client identified as ::ffff:192.168.1.126
[KPBLOQ] <= ehlo ip-192-168-1-126.ap-south-1.compute.internal
[KPBLOQ] => 250-My capabilities are
[KPBLOQ] => 250-STARTTLS
[KPBLOQ] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[KPBLOQ] <= STARTTLS
[KPBLOQ] => 220 Ready to start TLS
[KPBLOQ] <= ehlo ip-192-168-1-126.ap-south-1.compute.internal
[KPBLOQ] => 250-My capabilities are
[KPBLOQ] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[KPBLOQ] <= AUTH CRAM-MD5
[KPBLOQ] => 334 xxxxx=
[KPBLOQ] <= yyyyy=
[KPBLOQ] => 235 Granted for zerodha/zerodha-coin
[KPBLOQ] <= mail FROM:<noreply@domain.com>
[KPBLOQ] => 250 OK
[KPBLOQ] <= rcpt TO:<john@doe.com>
[KPBLOQ] Added external address 'john@doe.com'
[KPBLOQ] => 250 OK
[KPBLOQ] <= data
[KPBLOQ] => 354 Go ahead
[KPBLOQ] <= Content-Type: multipart/mixed; boundary="===============1042903233914275057=="
[KPBLOQ] Not logging further message data.
[KPBLOQ] => 530 From/Sender name is not valid
[KPBLOQ] <= rset
[KPBLOQ] => 250 OK```

As you can see in the logs, it did respond 250 OK for the given From address. Same credentials and same from address works for other programs. I have a feeling this is because of some header that's sent by the client. But not able to pinpoint what it is.

**Comment by vishnus** [comment]
Hi @willpower232 

We also encountered a similar issue, but not every all systems. Some python smtp lib programs, and recently https://bigbluebutton.org/ 's SMTP test mails are unable to send mails through postal and it gives same error:
```
[KPBLOQ]    Connection opened from ::ffff:192.168.1.126
[KPBLOQ]    Client identified as ::ffff:192.168.1.126
[KPBLOQ] <= ehlo ip-192-168-1-126.ap-south-1.compute.internal
[KPBLOQ] => 250-My capabilities are
[KPBLOQ] => 250-STARTTLS
[KPBLOQ] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[KPBLOQ] <= STARTTLS
[KPBLOQ] => 220 Ready to start TLS
[KPBLOQ] <= ehlo ip-192-168-1-126.ap-south-1.compute.internal
[KPBLOQ] => 250-My capabilities are
[KPBLOQ] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[KPBLOQ] <= AUTH CRAM-MD5
[KPBLOQ] => 334 xxxxx=
[KPBLOQ] <= yyyyy=
[KPBLOQ] => 235 Granted for organization/smtp
[KPBLOQ] <= mail FROM:<noreply@domain.com>
[KPBLOQ] => 250 OK
[KPBLOQ] <= rcpt TO:<john@doe.com>
[KPBLOQ] Added external address 'john@doe.com'
[KPBLOQ] => 250 OK
[KPBLOQ] <= data
[KPBLOQ] => 354 Go ahead
[KPBLOQ] <= Content-Type: multipart/mixed; boundary="===============1042903233914275057=="
[KPBLOQ] Not logging further message data.
[KPBLOQ] => 530 From/Sender name is not valid
[KPBLOQ] <= rset
[KPBLOQ] => 250 OK```

As you can see in the logs, it did respond 250 OK for the given From address. Same credentials and same from address works for other programs. I have a feeling this is because of some header that's sent by the client. But not able to pinpoint what it is.

**Comment by willpower232** [comment]
Looking at the code, that is where the email address is validated. You're right in saying that it could be validated earlier however it doesn't change the fact that you're trying to send from a domain that is not associated with the credential so that needs to be sorted.
